[NbConvertApp] Converting notebook mkstapylton@gmail.com-mattS-qiime2.ipynb to latex
/hpc/packages/minerva-centos7/python/3.7.3/bin/python: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/hpc/users/stapym01/.conda/envs/jupyter/bin/jupyter-nbconvert", line 10, in <module>
    sys.exit(main())
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/exporters/latex.py", line 88, in from_notebook_node
    return super(LatexExporter, self).from_notebook_node(nb, resources, **kw)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 307, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 403, in preprocess
    with self.setup_preprocessor(nb, resources, km=km):
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 345, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(**kwargs)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 296, in start_new_kernel
    kc.wait_for_ready(timeout=self.startup_timeout)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/jupyter_client/utils.py", line 26, in wrapped
    raise e
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/jupyter_client/utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/hpc/users/stapym01/.conda/envs/jupyter/lib/python3.9/site-packages/jupyter_client/client.py", line 180, in _async_wait_for_ready
    raise RuntimeError("Kernel died before replying to kernel_info")
RuntimeError: Kernel died before replying to kernel_info
